# ====== ACCOUNT CONFIGURATION ======
account:
  username: username
  password: password

# ====== ALGORITHM CONFIGURATION ======
AlgortihmName:
  currencies:
    - currency_name
  range_of_values: int
