# ====== ACCOUNT CONFIGURATION ======
account:
  username: username
  password: password

# ====== ALGORITHM CONFIGURATION ======
AlgortihmName:
  currencies:                  # currencies to analyse
    - currency_name
  range_of_values: int         # length of dataframe gathered from csv
  timeframe: int               # seconds of timeframe
  update_freq: int             # timeframe of closing prices, simulating the bot
  duplicate_protection: int    # n times the timeframe of remove zone
  stop_loss: null
  take_profit: null
