USE_THIS: false
# ~~~ * ACCOUNT CONFIGURATION * ~~~
credentials:
  username: str
  password: str
# ~~~ * ACCOUNT CONFIGURATION * ~~~
account:
  initial_config: int
  count_margin: boolean
  simulate_profit: boolean
# ~~~ * ACCOUNT CONFIGURATION * ~~~
algo:
  instruments:
    - str
  timeframe: int
# ~~~ * ACCOUNT CONFIGURATION * ~~~
plotters:
  - str
# ~~~ * ACCOUNT CONFIGURATION * ~~~
feeders:
  str:
    - str