# ====== ENGINE CONFIGURATION ======
engine:
    algorithms:
        - AlgorithmName

# ====== ACCOUNT CONFIGURATION ======
account:
  username: username
  password: password
  initial_balance: int

# ====== ALGORITHM CONFIGURATION ======
AlgortihmName:
  currencies:                  # currencies to analyse
    - currency_name
  range_of_values: int         # length of dataframe gathered from csv
  start_analysis: int          # start time of analysis with seconds * from now
  timeframe: int               # seconds of timeframe
  update_freq: int             # timeframe of closing prices, simulating the bot
  duplicate_protection: int    # n times the timeframe of remove zone
  stop_loss: null
  take_profit: null
  save_for_eff: boolean
  load_for_eff: boolean
