# ====== ACCOUNT CONFIGURATION ======
account:
  username: username
  password: password

# ====== ALGORITHM CONFIGURATION ======
AlgortihmName:
  currencies:
    - currency_name
  range_of_values: int
  trigger:
    name: name_of_trigger
    arguments:
      argument: arg
  indicators:
    - name: name_of_indicator
      arguments:
        argument: arg
      scope: scope