# ====== ACCOUNT CONFIGURATION ======
account:
  username: username
  password: password

# ====== ALGORITHM CONFIGURATION ======
AlgortihmName:
  currencies:
    - currency_name
  range_of_values: int         # length of dataframe gathered from csv
  timeframe: int               # seconds of timeframe
  duplicate_protection: int    # n times the timeframe of remove zone
