USE_THIS: false
# ====== ENGINE CONFIGURATION ======
engine:
    algorithms:
        - AlgorithmName

# ====== ACCOUNT CONFIGURATION ======
account:
  username: username
  password: password
  initial_balance: int

# ====== ALGORITHM CONFIGURATION ======
AlgortihmName:
  instruments:                  # instruments to analyse
    - instrument_name
  range_of_values: int         # length of dataframe gathered from csv
  start_analysis: int          # start time of analysis with seconds * from now
  timeframe: int               # seconds of timeframe
  update_freq: int             # timeframe of closing prices, simulating the bot
  duplicate_protection: int    # n times the timeframe of remove zone
  stop_loss: null
  take_profit: null
  save_for_eff: boolean
  load_for_eff: boolean

credentials:
  username: asd
  password: asd
account:
  initial_config: 1000
  count_margin: false
  simulate_profit: true
algo:
  instruments:
    - EURUSD
    - USDJPY
  timeframe: 300
plotters:
  - CDSPLT
feeders:
  CDSPLT:
    - ZIPF01